import sys
import Naked.toolshed.shell
from Naked.toolshed.shell import execute_js, muterun_js

#Test Script for largesum.js
#We pledge our honor that we have abided by the Stevens Honor System.
#Zach Saegesser
#Aimal Wajihuddin
#Ryan Edelstein
NUM_FILES = 10

def getListNums(str):
    return str.splitlines()

def addStuff(str):
    answer = 0
    for num in str:
        number = int(num)
        answer += number
    return answer;

def readOutput(i):
    file = open("output"+str(i)+".txt", "r")
    return file.read()

def generateTestOutputs():
    for i in range(1,NUM_FILES + 1):
        file = open("test" + str(i) + ".txt", "r")
        lst = getListNums(file.read())
        file.close()
        fullnumanswer = addStuff(lst)
        firsttenanswer = str(fullnumanswer)[0:10]
        rightanswer = "Full sum: " + str(fullnumanswer) +"\nFirst 10 digits: " + str(firsttenanswer)
        file2 = open("output" + str(i) + ".txt", "w")
        file2.write(rightanswer)
        file.close()

#generateTestOutputs()

for i in range(1, NUM_FILES + 1):
    file3 = open("output" + str(i) + ".txt", "r")
    a = file3.read()
    file3.close()
    jsanswer = str(muterun_js('../largesum.js', arguments = "-test "+str(i)).stdout)
    jsanswer = jsanswer[0:len(jsanswer)-1]

    if (a == jsanswer):
        print "Test " + str(i) + " PASS\n"
        print("Answer generated by largesum.js\n" + jsanswer +  '\n' + "Actual answer:\n" +  a + "\n\n")
    else:
        print(jsanswer, '\n', a)
        print "Test " + str(i) + " FAIL\n"
        print("Answer generated by largesum.js\n" + jsanswer +  '\n' + "Actual answer:\n" +  a + "\n\n")
        break;
